version: '3.7'

services:
  gtd_notion_manager:
    build: .
    init: true
    image: gtd_notion_manager
    container_name: gtd_notion_manager
    restart: unless-stopped
    environment:
      - TZ
      - GTD_DATABASE_ID
      - BEARER_SECRET
      - DELETION_DAYS
      - COMMENT_DAYS
      - CRON_FREQUENCY_DAYS
